### ISSUE TITLE
[Q] Please provide the a sample kubernetes manifest file, I am trying to implement this in a kubernetes cluster.

### ISSUE THREAD

**Issue by deena9291** [go-graphite/go-carbon#390]
I am currently using the python version of the attached graphite manifest which is dropping most of the metrics and has lot of performance issues.
[graphite-statsd-deployment.txt](https://github.com/go-graphite/go-carbon/files/5592893/graphite-statsd-deployment.txt)

**Comment by deniszh** [comment]
@deena9291 : 
You can use same manifest but enable go-carbon:
```
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: graphite
 name: graphite
 namespace: graphite
spec:
 replicas: 1
 selector:
   matchLabels:
     app: graphite
 template:
   metadata:
     labels:
       app: graphite
   spec:
    containers:
      - name: graphite
        image: graphiteapp/graphite-statsd:1.1.7-8-pypy
        env:
        - name: REDIS_TAGDB
          value: "1" 
        - name: GOCARBON
          value: "1"
       ports:
       - containerPort: 2003
         name: carbon-plain
       - containerPort: 2004
         name: carbon-pkl   
       - containerPort: 2023
         name: carbon-ag-plain
       - containerPort: 2024
         name: carbon-ag-pkl   
       - containerPort: 8125
         name: statsd   
       - containerPort: 8126
         name: statsd-admin  
       - containerPort: 80
         name: http
       volumeMounts:
         - name: graphite-storage
           mountPath: /opt/graphite/storage/
     volumes:
       - name: graphite-storage
         persistentVolumeClaim:
           claimName: graphite-pvc    
---
apiVersion: v1
kind: Service
metadata:
 name: graphite
 namespace: graphite
 labels:
   app: graphite
spec:
 type: NodePort
 ports:
 - port: 80
   protocol: TCP
   targetPort: 80
   name: http
 - port: 2003
   protocol: TCP
   targetPort: 2003
   name: carbon
 selector:
   app: graphite
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: graphite
  name: graphite-ingress
  labels:
    app: graphite-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
      - graphite.us-east-1.<xxxxxxxxxxx>.aws.com
      secretName: <xxxxxxxxxxx>
  rules:
    - host: graphite.us-east-1.<xxxxxxxxxxx>.aws.com
      http:
        paths:
          - path: /
            backend:
              serviceName: graphite
              servicePort: 80
```
